engines:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .eslintrc.js
      extensions:
      - .js

exclude_paths:
- android/
- ios/
- src/components/Icons/lib
checks:
 similar-code:
    enabled: false
