# source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTBlob',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket'
]

pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
pod 'RNI18n', :path => '../node_modules/react-native-i18n'
pod 'RNSVG', :path => '../node_modules/react-native-svg'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

pod 'GoogleMaps', '2.5.0'
pod 'react-native-maps', :path => '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'

pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

pod 'Firebase/Core'
pod 'Firebase/Messaging'

pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

pod 'lottie-ios', :path => '../node_modules/lottie-ios'
pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

target 'oteApp'
target 'oteAppTests'

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == "React"
#       target.remove_from_project
#     end
#   end
# end
