# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to play store beta"
  lane :beta do
    increment_version_code
    gradle(task: "assembleRelease")
    supply(
        track: "beta"
    )
    # crashlytics
  end

  desc "Submit a new alpha Build to play store beta"
  lane :alpha do
    increment_version_code
    gradle(task: "assembleRelease")
    supply(
    	track: "alpha"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    increment_version_code
    gradle(task: "assembleRelease")
    supply(
        track: "production"
    )
  end
end
